### ISSUE TITLE
non-descriptive error for string interpolation

### ISSUE THREAD

**Issue by coffeeowl** [breuleux/earl-grey#17]
This comes right from the REPL:
> ''
E.syntax.failure
The macro expected something different (could not locate error in the source).

The problem is  - it is very hard to locate such mistakes in a project with multiple modules. It doesn't say what macro fails, doesn't say where. I spend a lot of time writing CoffeeScript and as a result I do a lot of such mistakes because of the reversed syntax :-)

**Comment by breuleux** [comment]
I never realized `''` was an error, that's embarrassing. I really need to work on test coverage. Anyway, I fixed it on master.

Yeah, the error message is misleading, especially since it does usually tell you approximately where it happens (it highlights `''` with line/column, doesn't it?) For the most part this error indicates a failure on the macro implementer's side, not on your side: either a failure in the implementation, or a failure to provide an informative error message.

I've pushed some improvements to the default error messages. The error message you came upon would now look like this, which I think is better:

    E.syntax.failure: An error occurred in the `'` macro. You should bug the macro/language implementer to fix this.
